Auth
CruelDwemer/explosive-kittens pull request #3
Opened 2024-08-24 15:44 UTC by ilyavorozhtsov39

Базовая структура

2024-08-26 10:34 UTC, CruelDwemer requested changes

2024-08-26 10:34 UTC, CruelDwemer commented on packages/client/src/shared/ui/auth-input-element/auth-input-element.tsx
> +        onChange={e => setInput(e.target.value)}
Здесь лучше не использовать arrow function непосредственно в отрисовке, так как это влияет на производительность

https://stackoverflow.com/questions/48699573/correct-use-of-arrow-functions-in-react

2024-08-26 10:38 UTC, ryabayeah commented on packages/client/src/App.tsx
App файл в fsd обычно кладут в app папку

2024-08-26 10:40 UTC, ryabayeah commented on packages/client/src/App.tsx
> +import Register from './pages/register/register'
Лучше сделай в pages файл index.ts, откуда будешь экспортировать все имеющиеся страницы
таким образом у тебя не будет кучи имортов со страницами, а будет единый импорт
------
Например
Было: 
`import Login from './pages/login/login'
import Register from './pages/register/register'
`
Стало
`import {Login, Register} from './pages'`

Так мы сокращаем кол-во строк\импортов и улучшаем читаемость кода)

2024-08-26 10:42 UTC, ryabayeah commented on packages/client/src/pages/login/login.tsx
Хорошим решением будет и тут сделать index.ts файл, куда ты будешь импортировать то, что в твоей папке login можно экспортировать
Т.е.
1. Заводишь в папке index.ts
2. Импортируешь и сразу экспортируешь оттуда login страницу
3. Удобно используешь компонент где угодно без этого огромного пути /pages/login/login

2024-08-26 10:43 UTC, ryabayeah commented on packages/client/src/pages/register/register.module.scss
https://github.com/CruelDwemer/explosive-kittens/pull/3/files?diff=split&w=0#r1731059202

2024-08-26 10:43 UTC, ryabayeah commented on packages/client/src/pages/login/login.tsx
> +]
Такие вещи лучше выносить в отдельные файлы-константы, а не хранить у компонента

Разделяй и властвуй

2024-08-26 10:45 UTC, ryabayeah commented on packages/client/src/pages/login/login.tsx
> +import AuthForm from '../../shared/ui/auth-form/auth-form'
Аналогично комментариям ранее
Лучше сделать в shared/ui файл index.ts, откуда ты будешь экспортировать все ui
И тогда у тебя не будет этого длинного пути` /shared/ui/auth-form/auth-form`, а будет просто `/shared/ui`

2024-08-26 10:45 UTC, ryabayeah commented on packages/client/src/pages/register/register.tsx
> +]
Такие вещи лучше выносит в отдельные файлы-константы

2024-08-26 10:51 UTC, ryabayeah commented on packages/client/src/App.tsx
>  function App() {
Как совет - лучше использовать стрелочные функции - их удобнее типизировать чем простые function и они более читаемы

Например
```
interface MyComponentProps{
title: string
}
const MyComponent: FC<MyComponentProps> = ({title}) => {
return <div>title</div>
....
}
```
Здесь FC - это типизация того, что наша функция вернет ФункциональныйКомпонент (FunctionComponent) и принимает пропсы MyComponentProps
А с простой функцией не так читаемо
```
interface MyComponentProps{
title: string
}
function MyComponent({title}: FC<MyComponentProps> ){
return <div>title</div>
....
}
```

2024-08-26 10:51 UTC, ryabayeah commented on packages/client/src/pages/login/login.tsx
> +export default function Login() {
Лучше не использовать default, т.к. потом при рефакторинге будет тяжелее отследить изменения

2024-08-26 10:51 UTC, ryabayeah commented on packages/client/src/pages/login/login.tsx
> +export default function Login() {
https://github.com/CruelDwemer/explosive-kittens/pull/3/files?diff=split&w=0#r1731067265

2024-08-26 10:52 UTC, ryabayeah commented on packages/client/src/pages/register/register.tsx
> +export default function Login() {
Лучше не использовать default, потому что при рефакторинге будет труднее отследить изменения
https://github.com/CruelDwemer/explosive-kittens/pull/3/files?diff=split&w=0#r1731067265

2024-08-26 10:52 UTC, ryabayeah commented on packages/client/src/shared/ui/auth-button/auth-button.tsx
> +export default function AuthButton({ text }: T) {
Лучше не использовать default, потому что при рефакторинге будет труднее отследить изменения
Плюс стоит рассмотреть стрелочный подход =>
https://github.com/CruelDwemer/explosive-kittens/pull/3/files?diff=split&w=0#r1731067265

2024-08-26 10:54 UTC, ryabayeah commented on packages/client/src/shared/ui/auth-button/auth-button.tsx
> +export default function AuthButton({ text }: T) {
Ты можешь просто назвать это Button и передавать в качестве пропса тип кнопки
Так можно сделать универсальный UIKit компонент

2024-08-27 14:06 UTC, arishkaa05 approved these changes

2024-08-27 14:12 UTC, arishkaa05 approved these changes

2024-08-31 07:29 UTC, CruelDwemer approved these changes

2024-09-01 05:31 UTC, ryabayeah approved these changes

2024-09-01 05:32 UTC, merged