Добавила экран с началом игры
CruelDwemer/explosive-kittens pull request #5
Opened 2024-09-02 07:21 UTC by arishkaa05

### Какую задачу решаем
Сверстать экран с началом игры — например, обратный отсчёт, лоадер, экран с подсказками о том, как играть, или просто кнопка «Старт»
<img width="600" alt="Снимок экрана 2024-09-02 в 10 17 52" src="https://github.com/user-attachments/assets/058e217e-d0ad-48c6-8e32-56d8fc0ba7e9">
<img width="770" alt="Снимок экрана 2024-09-02 в 10 21 04" src="https://github.com/user-attachments/assets/d4f8bd3d-9aca-4207-a4da-1b8763b5aa60">
<img width="764" alt="Снимок экрана 2024-09-02 в 10 21 07" src="https://github.com/user-attachments/assets/3755a3b7-4f7e-42ad-b0ae-4c74c3bf6d63">

### Скриншоты/видяшка (если есть)

Добавлен роут для игры /play, при переходе по этому роуту юзер имеет возможность начать игру:

- при вводе названия игра создается лобби 

- добавляются участники

- если участников больше 2 можно запустить игру

- при запуске обратный отсчет с 3 и перебрасывает на саму игру (пока на пустой роут /start)

2024-09-03 07:13 UTC, dergunovmxm approved these changes

2024-09-03 07:13 UTC, dergunovmxm commented on packages/client/src/widgets/add-player.tsx
> +  const createNewPlay = async (playName: string) => {
Как-будто бы все нижеперечисленные методы нужно вынести в отдельный файл такому пути entites/dir_name/api/api.ts

2024-09-04 12:26 UTC, CruelDwemer approved these changes

2024-09-05 17:23 UTC, IvanPeleshok requested changes
Добрый день!

Классная работа
Есть некоторые замечания
Предлагаю ознакомиться и поправить

Хорошего дня :)

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/entities/lobby/api/lobby-api.ts
> +const BASE_URL = 'https://ya-praktikum.tech/api/v2'
Предлагаю выносить переменные, которые повторяются куда-нибудь на общий уровень для переиспользования

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/entities/lobby/api/lobby-api.ts
> +  return fetch(`${BASE_URL}/chats`, {
Для запросов предлагаю обратить внимание на axios

Достаточно сгенерировать экземпляр с конфигурацией и использовать его по необходимости (существенно сокращает код, доступное апи) https://axios-http.com/ru/docs/instance

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/entities/user/api/user-api.ts
> +const BASE_URL = 'https://ya-praktikum.tech/api/v2'
Замечание выше

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/pages/play/play.tsx
> +  const handleOpen = () => setOpen(true)
Здорово, что выносите обработчики в константы

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/pages/play/play.tsx
> +          return prevCount - 1
Если используется return, то конструкция if / else теряет смысл, т.к есть ранний выход (предлагаю поправить все похожие момент в рамках PR)

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/pages/play/play.tsx
> +    const intervalId = setInterval(() => {
Если это анимация, то лучше использовать requestAnimationFrame  https://learn.javascript.ru/js-animation

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/widgets/add-player.tsx
> +    console.log(playName)
Отладку полагаю можно убрать

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/widgets/add-player.tsx
> +    const response = await createPlay(playName)
Никак не обрабатываете исключения из промисса
Предлагаю доработать с использование try / catch https://learn.javascript.ru/exception

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/widgets/add-player.tsx
> +      const newUserList = data.map((item: { login: string; id: number }) => ({
Маппинг лучше вынести в отдельный хелпер для читаемости и удобства с точки зрения тестирования (рекомендация)

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/widgets/add-player.tsx
> +  const handleSelectUser = (event: any, newValue: any) => {
Типизируем, any быть не должно (посмотреть во всём PR)

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/widgets/add-player.tsx
> +  const handlePlayNameChange = (e: {
Предлагаю использовать типы React или либ, которые используете
Полагаю, что @mui/material имеет типы компонентов

Дополнительно, предлагаю не сокращать наименование переменных (event)

2024-09-05 17:23 UTC, IvanPeleshok commented on packages/client/src/widgets/add-player.tsx
> +                {players.map((player: any) => (
any не используем

2024-09-06 19:22 UTC, arishkaa05 commented on packages/client/src/entities/lobby/api/lobby-api.ts
> +const BASE_URL = 'https://ya-praktikum.tech/api/v2'
Вынесла в shared/constants/api.ts

2024-09-06 19:23 UTC, arishkaa05 commented on packages/client/src/entities/lobby/api/lobby-api.ts
> +  return fetch(`${BASE_URL}/chats`, {
Решение использовать fetch было принято командой

2024-09-06 19:24 UTC, arishkaa05 commented on packages/client/src/pages/play/play.tsx
> +          return prevCount - 1
Заменила код, больше таких моментов не нашла

2024-09-06 19:25 UTC, arishkaa05 commented on packages/client/src/widgets/add-player.tsx
> +    const response = await createPlay(playName)
Обработала все промиссы

2024-09-06 19:25 UTC, arishkaa05 commented on packages/client/src/widgets/add-player.tsx
> +      const newUserList = data.map((item: { login: string; id: number }) => ({
Вынесла в файл helpers.tsx

2024-09-06 19:25 UTC, arishkaa05 commented on packages/client/src/widgets/add-player.tsx
> +  const handleSelectUser = (event: any, newValue: any) => {
Исправила

2024-09-06 19:25 UTC, arishkaa05 commented on packages/client/src/pages/play/play.tsx
> +    const intervalId = setInterval(() => {
Заменила на requestAnimationFrame

2024-09-07 20:01 UTC, IvanPeleshok approved these changes
Поздравляю, работа принята!

Хорошего дня :)

2024-09-08 07:03 UTC, merged